### PR TITLE
Allow only message mode, make call method name shorter.

### PR DESCRIPTION
**Pull request by DrMundo0**
// Only message
var toast = app.toast('A long long message', '', {});

// Show
toast.show();

// Show with message
toast.show("message");

// Hide
toast.hide();

### CODE REVIEW

**Comment by valnub** [comment]
Hi, thanks for your PR. I'm currently a little busy but I'll review it in September and might merge it then.

**Comment by DrMundo0** [comment]
It doesn't matter. :smiley:

**Comment by valnub** [comment]
I looked into your code and it looks alright. Could you please also **update README** with information about new `show(message)` and `hide()` methods? I'll merge your PR after that.

Also, I noticed that your example **has errors**. Seems like it cannot find a css file, please recheck:

bildschirmfoto 2015-10-05 um 15 00 08

**Comment by DrMundo0** [comment]
Hi, I've fixed the css not exists error, and update README.

**Comment by valnub** [comment]
Great, thanks :)
Merged

**Comment by DrMundo0** [comment]
:+1::+1:

**Pull request merged**
